#!/bin/bash

WORD_CHARS="A-Za-z0-9',!.&/—-"
DICTIONARY="/usr/share/dict/linux.words"
if [ ! -f $DICTIONARY ]; then DICTIONARY="linux.words"; fi

tr -cs "$WORD_CHARS" '[\n*]' | \
  sort -u | \
  #tee /dev/tty | \
  comm -23 - <(sort "$DICTIONARY")

